// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type CartInput struct {
	ItemID   int `json:"itemID"`
	Quantity int `json:"quantity"`
}

type CartItem struct {
	Quantity int   `json:"quantity"`
	Item     *Item `json:"item"`
}

type Catalog struct {
	ID     *int       `json:"id,omitempty"`
	Name   *string    `json:"name,omitempty"`
	Parent *Catalog   `json:"parent"`
	Childs []*Catalog `json:"childs"`
	Items  []*Item    `json:"items"`
}

type Item struct {
	ID          *int     `json:"id,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Parent      *Catalog `json:"parent"`
	Seller      *Seller  `json:"seller"`
	InCart      int      `json:"inCart"`
	InStockText string   `json:"inStockText"`
}

type Mutation struct {
}

type Query struct {
}

type Seller struct {
	ID    *int    `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Deals int     `json:"deals"`
	Items []*Item `json:"items"`
}
